//I've used REST Client 
POST http://localhost:2525/videos
content-type: application/json

{
    "title": "Video NODE",
    "description": "macrebs node",
    "duration": 2000
}

###

GET  http://localhost:2525/videos

###

GET http://localhost:2525/videos?search=node

###

PUT http://localhost:2525/videos/79accfdc-9ffa-4341-a51c-f8c55af33731
content-type: application/json

{
    "title": "Video Macrebs +",
    "description": "Macrebs plus",
    "duration": 260
}

###

DELETE http://localhost:2525/videos/79accfdc-9ffa-4341-a51c-f8c55af33731
