//I've used REST Client 
POST http://localhost:2525/videos
content-type: application/json

{
    "title": "Video Macrebs",
    "description": "macrebs",
    "duration": 2000
}

###

GET  http://localhost:2525/videos

###

GET http://localhost:2525/videos?abacate=node

###

PUT http://localhost:2525/videos/d32eac95-f96a-4e9e-8baf-58321d06a90c
content-type: application/json

{
    "title": "Video node",
    "description": "Macrebs video",
    "duration": 130
}

###

DELETE http://localhost:2525/videos/d32eac95-f96a-4e9e-8baf-58321d06a90c
